### ISSUE TITLE
place_algo_order is missing a lot of arguments

### ISSUE THREAD

**Issue by dignitas123** [nicelgueta/pyokx#3]
POST /api/v5/trade/order-algo accepts more arguments, that are necessary to make an order.

https://www.okx.com/docs-v5/en/#rest-api-trade-place-algo-order

F.e. it's missing a 'triggerPx'

**Comment by nicelgueta** [comment]
Hi - thanks for reaching out with your feedback. There was some faulty logic in the scraper that generates this code that missed certain tables of parameters and was only picking up the first one. This should be fixed now in 0.5.0, specifically with place_algo_order now having the parameter you require. Let me know of further issues. thanks
